// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: daemon.proto

package daemonpb

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentGateD_AcquireSession_FullMethodName = "/agentgate.AgentGateD/AcquireSession"
	AgentGateD_ReleaseSession_FullMethodName = "/agentgate.AgentGateD/ReleaseSession"
	AgentGateD_EvaluateHook_FullMethodName   = "/agentgate.AgentGateD/EvaluateHook"
	AgentGateD_Status_FullMethodName         = "/agentgate.AgentGateD/Status"
)

// AgentGateDClient is the client API for AgentGateD service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentGateD is the agent-gate daemon service.
// The claude wrapper and all hook processes connect here.
type AgentGateDClient interface {
	// AcquireSession is called by the claude wrapper before launching claude.
	// The daemon creates a fake HOME in XDG_RUNTIME_DIR, populates settings.json
	// with the session model injected, and returns the path.
	AcquireSession(ctx context.Context, in *AcquireSessionRequest, opts ...grpc.CallOption) (*AcquireSessionResponse, error)
	// ReleaseSession is called by the claude wrapper after claude exits.
	// The daemon cleans up the fake HOME and any associated runtime state.
	ReleaseSession(ctx context.Context, in *ReleaseSessionRequest, opts ...grpc.CallOption) (*ReleaseSessionResponse, error)
	// EvaluateHook forwards raw hook input to the daemon-owned enforcement engine.
	EvaluateHook(ctx context.Context, in *EvaluateHookRequest, opts ...grpc.CallOption) (*EvaluateHookResponse, error)
	// Status returns process and build metadata for the connected daemon.
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type agentGateDClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentGateDClient(cc grpc.ClientConnInterface) AgentGateDClient {
	return &agentGateDClient{cc}
}

func (c *agentGateDClient) AcquireSession(ctx context.Context, in *AcquireSessionRequest, opts ...grpc.CallOption) (*AcquireSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcquireSessionResponse)
	err := c.cc.Invoke(ctx, AgentGateD_AcquireSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentGateDClient) ReleaseSession(ctx context.Context, in *ReleaseSessionRequest, opts ...grpc.CallOption) (*ReleaseSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseSessionResponse)
	err := c.cc.Invoke(ctx, AgentGateD_ReleaseSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentGateDClient) EvaluateHook(ctx context.Context, in *EvaluateHookRequest, opts ...grpc.CallOption) (*EvaluateHookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvaluateHookResponse)
	err := c.cc.Invoke(ctx, AgentGateD_EvaluateHook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentGateDClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, AgentGateD_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentGateDServer is the server API for AgentGateD service.
// All implementations must embed UnimplementedAgentGateDServer
// for forward compatibility.
//
// AgentGateD is the agent-gate daemon service.
// The claude wrapper and all hook processes connect here.
type AgentGateDServer interface {
	// AcquireSession is called by the claude wrapper before launching claude.
	// The daemon creates a fake HOME in XDG_RUNTIME_DIR, populates settings.json
	// with the session model injected, and returns the path.
	AcquireSession(context.Context, *AcquireSessionRequest) (*AcquireSessionResponse, error)
	// ReleaseSession is called by the claude wrapper after claude exits.
	// The daemon cleans up the fake HOME and any associated runtime state.
	ReleaseSession(context.Context, *ReleaseSessionRequest) (*ReleaseSessionResponse, error)
	// EvaluateHook forwards raw hook input to the daemon-owned enforcement engine.
	EvaluateHook(context.Context, *EvaluateHookRequest) (*EvaluateHookResponse, error)
	// Status returns process and build metadata for the connected daemon.
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	mustEmbedUnimplementedAgentGateDServer()
}

// UnimplementedAgentGateDServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentGateDServer struct{}

func (UnimplementedAgentGateDServer) AcquireSession(context.Context, *AcquireSessionRequest) (*AcquireSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcquireSession not implemented")
}
func (UnimplementedAgentGateDServer) ReleaseSession(context.Context, *ReleaseSessionRequest) (*ReleaseSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseSession not implemented")
}
func (UnimplementedAgentGateDServer) EvaluateHook(context.Context, *EvaluateHookRequest) (*EvaluateHookResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EvaluateHook not implemented")
}
func (UnimplementedAgentGateDServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedAgentGateDServer) mustEmbedUnimplementedAgentGateDServer() {}
func (UnimplementedAgentGateDServer) testEmbeddedByValue()                    {}

// UnsafeAgentGateDServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentGateDServer will
// result in compilation errors.
type UnsafeAgentGateDServer interface {
	mustEmbedUnimplementedAgentGateDServer()
}

func RegisterAgentGateDServer(s grpc.ServiceRegistrar, srv AgentGateDServer) {
	// If the following call panics, it indicates UnimplementedAgentGateDServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentGateD_ServiceDesc, srv)
}

func _AgentGateD_AcquireSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcquireSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentGateDServer).AcquireSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentGateD_AcquireSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentGateDServer).AcquireSession(ctx, req.(*AcquireSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentGateD_ReleaseSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentGateDServer).ReleaseSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentGateD_ReleaseSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentGateDServer).ReleaseSession(ctx, req.(*ReleaseSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentGateD_EvaluateHook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluateHookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentGateDServer).EvaluateHook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentGateD_EvaluateHook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentGateDServer).EvaluateHook(ctx, req.(*EvaluateHookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentGateD_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentGateDServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentGateD_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentGateDServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentGateD_ServiceDesc is the grpc.ServiceDesc for AgentGateD service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentGateD_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agentgate.AgentGateD",
	HandlerType: (*AgentGateDServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AcquireSession",
			Handler:    _AgentGateD_AcquireSession_Handler,
		},
		{
			MethodName: "ReleaseSession",
			Handler:    _AgentGateD_ReleaseSession_Handler,
		},
		{
			MethodName: "EvaluateHook",
			Handler:    _AgentGateD_EvaluateHook_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _AgentGateD_Status_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "daemon.proto",
}
