// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: daemon.proto

package daemonpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EvaluateHookRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// raw_json is the raw JSON payload read from hook stdin.
	RawJson []byte `protobuf:"bytes,1,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
	// provider_hint is a best-effort CLI/template hint such as "codex" or
	// "gemini". Daemon-side detection may override it based on env/payload.
	ProviderHint   string            `protobuf:"bytes,2,opt,name=provider_hint,json=providerHint,proto3" json:"provider_hint,omitempty"`
	Cwd            string            `protobuf:"bytes,3,opt,name=cwd,proto3" json:"cwd,omitempty"`
	Argv           []string          `protobuf:"bytes,4,rep,name=argv,proto3" json:"argv,omitempty"`
	EnvFingerprint map[string]string `protobuf:"bytes,5,rep,name=env_fingerprint,json=envFingerprint,proto3" json:"env_fingerprint,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EvaluateHookRequest) Reset() {
	*x = EvaluateHookRequest{}
	mi := &file_daemon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateHookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateHookRequest) ProtoMessage() {}

func (x *EvaluateHookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateHookRequest.ProtoReflect.Descriptor instead.
func (*EvaluateHookRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{0}
}

func (x *EvaluateHookRequest) GetRawJson() []byte {
	if x != nil {
		return x.RawJson
	}
	return nil
}

func (x *EvaluateHookRequest) GetProviderHint() string {
	if x != nil {
		return x.ProviderHint
	}
	return ""
}

func (x *EvaluateHookRequest) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *EvaluateHookRequest) GetArgv() []string {
	if x != nil {
		return x.Argv
	}
	return nil
}

func (x *EvaluateHookRequest) GetEnvFingerprint() map[string]string {
	if x != nil {
		return x.EnvFingerprint
	}
	return nil
}

type EvaluateHookResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// exit_code is the code the hook process should exit with.
	// 0 = allow, 2 = block.
	ExitCode int32 `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// stdout_data is written to hook process stdout.
	StdoutData []byte `protobuf:"bytes,2,opt,name=stdout_data,json=stdoutData,proto3" json:"stdout_data,omitempty"`
	// stderr_data is written to hook process stderr.
	StderrData    []byte `protobuf:"bytes,3,opt,name=stderr_data,json=stderrData,proto3" json:"stderr_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateHookResponse) Reset() {
	*x = EvaluateHookResponse{}
	mi := &file_daemon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateHookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateHookResponse) ProtoMessage() {}

func (x *EvaluateHookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateHookResponse.ProtoReflect.Descriptor instead.
func (*EvaluateHookResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{1}
}

func (x *EvaluateHookResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *EvaluateHookResponse) GetStdoutData() []byte {
	if x != nil {
		return x.StdoutData
	}
	return nil
}

func (x *EvaluateHookResponse) GetStderrData() []byte {
	if x != nil {
		return x.StderrData
	}
	return nil
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_daemon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{2}
}

type StatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Pid            int64                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	ExecutablePath string                 `protobuf:"bytes,2,opt,name=executable_path,json=executablePath,proto3" json:"executable_path,omitempty"`
	SocketPath     string                 `protobuf:"bytes,3,opt,name=socket_path,json=socketPath,proto3" json:"socket_path,omitempty"`
	Version        string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Commit         string                 `protobuf:"bytes,5,opt,name=commit,proto3" json:"commit,omitempty"`
	Dirty          string                 `protobuf:"bytes,6,opt,name=dirty,proto3" json:"dirty,omitempty"`
	BuildHash      string                 `protobuf:"bytes,7,opt,name=build_hash,json=buildHash,proto3" json:"build_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_daemon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{3}
}

func (x *StatusResponse) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *StatusResponse) GetExecutablePath() string {
	if x != nil {
		return x.ExecutablePath
	}
	return ""
}

func (x *StatusResponse) GetSocketPath() string {
	if x != nil {
		return x.SocketPath
	}
	return ""
}

func (x *StatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *StatusResponse) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *StatusResponse) GetDirty() string {
	if x != nil {
		return x.Dirty
	}
	return ""
}

func (x *StatusResponse) GetBuildHash() string {
	if x != nil {
		return x.BuildHash
	}
	return ""
}

var File_daemon_proto protoreflect.FileDescriptor

const file_daemon_proto_rawDesc = "" +
	"\n" +
	"\fdaemon.proto\x12\tagentgate\"\x9b\x02\n" +
	"\x13EvaluateHookRequest\x12\x19\n" +
	"\braw_json\x18\x01 \x01(\fR\arawJson\x12#\n" +
	"\rprovider_hint\x18\x02 \x01(\tR\fproviderHint\x12\x10\n" +
	"\x03cwd\x18\x03 \x01(\tR\x03cwd\x12\x12\n" +
	"\x04argv\x18\x04 \x03(\tR\x04argv\x12[\n" +
	"\x0fenv_fingerprint\x18\x05 \x03(\v22.agentgate.EvaluateHookRequest.EnvFingerprintEntryR\x0eenvFingerprint\x1aA\n" +
	"\x13EnvFingerprintEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"u\n" +
	"\x14EvaluateHookResponse\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x1f\n" +
	"\vstdout_data\x18\x02 \x01(\fR\n" +
	"stdoutData\x12\x1f\n" +
	"\vstderr_data\x18\x03 \x01(\fR\n" +
	"stderrData\"\x0f\n" +
	"\rStatusRequest\"\xd3\x01\n" +
	"\x0eStatusResponse\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x03R\x03pid\x12'\n" +
	"\x0fexecutable_path\x18\x02 \x01(\tR\x0eexecutablePath\x12\x1f\n" +
	"\vsocket_path\x18\x03 \x01(\tR\n" +
	"socketPath\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x16\n" +
	"\x06commit\x18\x05 \x01(\tR\x06commit\x12\x14\n" +
	"\x05dirty\x18\x06 \x01(\tR\x05dirty\x12\x1d\n" +
	"\n" +
	"build_hash\x18\a \x01(\tR\tbuildHash2\x9c\x01\n" +
	"\n" +
	"AgentGateD\x12O\n" +
	"\fEvaluateHook\x12\x1e.agentgate.EvaluateHookRequest\x1a\x1f.agentgate.EvaluateHookResponse\x12=\n" +
	"\x06Status\x12\x18.agentgate.StatusRequest\x1a\x19.agentgate.StatusResponseB%Z#goodkind.io/agent-gate/api/daemonpbb\x06proto3"

var (
	file_daemon_proto_rawDescOnce sync.Once
	file_daemon_proto_rawDescData []byte
)

func file_daemon_proto_rawDescGZIP() []byte {
	file_daemon_proto_rawDescOnce.Do(func() {
		file_daemon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_daemon_proto_rawDesc), len(file_daemon_proto_rawDesc)))
	})
	return file_daemon_proto_rawDescData
}

var file_daemon_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_daemon_proto_goTypes = []any{
	(*EvaluateHookRequest)(nil),  // 0: agentgate.EvaluateHookRequest
	(*EvaluateHookResponse)(nil), // 1: agentgate.EvaluateHookResponse
	(*StatusRequest)(nil),        // 2: agentgate.StatusRequest
	(*StatusResponse)(nil),       // 3: agentgate.StatusResponse
	nil,                          // 4: agentgate.EvaluateHookRequest.EnvFingerprintEntry
}
var file_daemon_proto_depIdxs = []int32{
	4, // 0: agentgate.EvaluateHookRequest.env_fingerprint:type_name -> agentgate.EvaluateHookRequest.EnvFingerprintEntry
	0, // 1: agentgate.AgentGateD.EvaluateHook:input_type -> agentgate.EvaluateHookRequest
	2, // 2: agentgate.AgentGateD.Status:input_type -> agentgate.StatusRequest
	1, // 3: agentgate.AgentGateD.EvaluateHook:output_type -> agentgate.EvaluateHookResponse
	3, // 4: agentgate.AgentGateD.Status:output_type -> agentgate.StatusResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_daemon_proto_init() }
func file_daemon_proto_init() {
	if File_daemon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_daemon_proto_rawDesc), len(file_daemon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_daemon_proto_goTypes,
		DependencyIndexes: file_daemon_proto_depIdxs,
		MessageInfos:      file_daemon_proto_msgTypes,
	}.Build()
	File_daemon_proto = out.File
	file_daemon_proto_goTypes = nil
	file_daemon_proto_depIdxs = nil
}
